# -*- coding: utf-8 -*-
"""charts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UsPrSLyUwY743oV30gEBjC0AcLBQTgxB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

x=np.array([1,2,3,4])
print(x)

y= np.array([[1,2],[3,5]])
print(y)

#3d array
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (z)

e=np.array([[[1,2],[3,4],[5,6]]])
print(e)

s=np.array([1,2,3,4],ndmin=10)
s

#zero array
v=np.zeros((3,3))
v

#ones array
onearray=np.ones((3,3))
onearray

#identical array and index must be square
d=np.eye(6)
d

dot=(d*5+8)%2
dot

#mean by using np array
x=np.array([1,2,3,4])
mean_value=np.mean(x)
mean_value

#
data={ 'model':np.arange(1970,2021),

    'weight':np.random.randint(2000,5000,51),
       'horsepower':np.random.randint(80,400,51),
       'mpg':np.random.uniform(10,40,51)
}

df=pd.DataFrame(data)
df

df.isnull().sum()

df.describe()

# line plot figure
plt.figure(figsize=(10,6))
plt.plot(df['model'],df['weight'],marker='o',linestyle='-')
plt.title('weight of cars over the year ')
plt.xlabel('model')
plt.ylabel('weight')
plt.grid(True)
plt.show()

# histmap plot figure
plt.figure(figsize=(10,5))
sns.scatterplot(x=df['model'],y=df['horsepower'])
plt.title('horsepower of cars over the year ')
plt.xlabel('model')
plt.ylabel('horsepower')

plt.show()

#histplot figure
plt.figure(figsize=(10,5))
sns.histplot(df['weight'],bins=10,kde=True)
plt.title('weight of cars over the year ')
plt.xlabel('weight')
plt.show()

#histplot figure
plt.figure(figsize=(10,5))
sns.histplot(df['weight'],bins=10,kde=False)
plt.title('weight of cars over the year ')
plt.xlabel('weight')
plt.show()

plt.figure(figsize=(10,5))
sns.heatmap(df.corr(),annot=True ,cmap='coolwarm')
plt.title('correlation heatmap')
plt.show()

df.to_csv('simulated_cars.csv',index=False)

